name: python-workshop
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9.4
  - pandas=1.3.3
  - matplotlib=3.4.3
    #  - pyreadline3=3.3
  - biopython=1.79
  - notebook
  - rise=5.7.1
  - jupyter_contrib_nbextensions=0.5.1
  - beautifulsoup4=4.10.0
  - fsspec=2021.10.0
  - openpyxl=3.0.9
