name: python-teacher
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pandas=3.0
  - matplotlib=3.11
  - biopython=1.88
  - notebook=7.6
  - jupyterlab_rise=0.43
  - beautifulsoup4=4.15
  - fsspec=2026.9.0
  - openpyxl=3.1
  - scikit-learn=1.9
