import random
import re

line = "MVRVVGWTLAMAALAGVMGQTTTTTTTTTESTMEASVESTTVASDSDSSCVSGGKVTLTAAGDDAAVLDSSCKKTPLTVETLAKTNRTLSAASLGIEQVTSVPDIDTLDLSWNSVSSMKDLSKNAPKLRKLVLMSNGLSSLDGISLPPTLEDLDLSTNPLGSISGLDKLPLRTLTITNSSVTDISKVSMPSSLETLNAAYNGLTKFPSTDSLKSLKTLTLTTNSLKSFKEITFPPAVTSIDLSWNFLSSFDGFELPSTVTKLYLGGNLFTSLSDMKISNDLTILYVHDMDIKSLDGVTFPDTVTALSLMNCSLSVIKETKLPSQLVYLDISENSITALPTQLPDSLRSITATNNKFTELTKIKFPSSITKLEFGGNQISKVAGIVFPLSLESAAFGDSVITEFEVSRSDYLMFQKTNSLNATIESTSCSNPAAEKGVYGKATLCVLPDDVFESLYGSRGEGNSKSSSSDGGSSSTWIIPVVISVIAVVGVVVGIFVYRKRKEKQAQEQKPLPTHFPQTLADPTVFGAMGDIKLNSTEMSSYHSMFGTGSGNGAVTSGGSNGPDQSLIKYRIPTNEITLQRALAKGGFGIVYLASYQSQDVVVKKILPEKSSDDRHLKAFLDEIKLCSTLNHAKIIKFIGVSWNTLSDIAVIMEYMSGGDLDTLLKKQHTRKAEYPGEFDWYASTMLPTKAQLALDVLEGVVYLHSFSSPIIHRDLKAKNVLLSDTYEAKLSDFGVSKEWRVDTTMTAGIGTMAWIAPEVLRGERYTEKADMYSFGVILTELATCSKPFDGVTNALIVLKVTSGEHRPDMGPDAPEDIRDLGLRCLSYNPMDRPSAMVAHYELKTLLKAHCSTFEL"
alphabet = list(set(line))

prob = 0.1
size = 1000

for x in range(size):
    print('>sequence_{}'.format(x))
    if random.random() <= prob:
        subst = random.choice(alphabet)
        newline = re.sub('TVET', 'TL{}T'.format(subst), line)
        print(newline)
    else:
        print(line)
