name: Check links

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 16 * *"


jobs:
  check_links:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Remove folders that do not care about broken links
        run: |
          rm -rf DevelopmentDesign

      - uses: gaurav-nelson/github-action-markdown-link-check@v1

      #- uses: lycheeverse/lychee-action@v1.2.0
      #  with:
      #    fail: true
